title: OSORI
description: Github Pages for OSORI
baseurl: ""
theme: just-the-docs
url: https://osori-db.github.io

color_scheme: dark_theme
logo: "/assets/images/ic_logo_osori.png"
favicon_ico: "/assets/images/favicon.ico"

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-multiple-languages-plugin

languages: ["ko", "en"]
exclude_from_localizations: ["javascript", "images", "css"]
languageNames:
  ko: 한국어
  en: English
  
isoLanguageCodes:
  ko: ko
  en: en_US

permalink: pretty

callouts_level: loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
